### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by xwmario** [vintagedaddyo/MyBB_Plugin-Prostats#1]
If you could provide support for using it with prostats!
https://github.com/mybbgroup/Thank-you-like-system
as well it would be great

**Comment by vintagedaddyo** [comment]
Well, as noted in the readme, it already has a compat thanks system ie: https://github.com/vintagedaddyo/MyBB_Plugin-Thanks

* also as I stopped doing mybb related projects awhile ago sorry until such a time if and or when I may ever find an interest or time to return to such there are no plans for focus on additional thanks system compats
